<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite0f29b8c26cb62c7b59bc50a021a5cf8
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite0f29b8c26cb62c7b59bc50a021a5cf8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite0f29b8c26cb62c7b59bc50a021a5cf8::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
